import type { Cell, PieceId, Placement } from './types';

/**
 * Base cell definitions for the 21 Blokus pieces, verbatim from GAME_SPEC §2.
 * Each shape is normalized so min x = min y = 0. Coordinates are (x = column, y = row).
 */
export const PIECES: Record<PieceId, Cell[]> = {
  // 1 square
  I1: [{ x: 0, y: 0 }],
  // 2 squares
  I2: [{ x: 0, y: 0 }, { x: 1, y: 0 }],
  // 3 squares
  I3: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }],
  V3: [{ x: 0, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }],
  // 4 squares
  I4: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }],
  O4: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }],
  T4: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 1, y: 1 }],
  L4: [{ x: 0, y: 0 }, { x: 0, y: 1 }, { x: 0, y: 2 }, { x: 1, y: 2 }],
  S4: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }],
  // 5 squares
  F5: [{ x: 1, y: 0 }, { x: 2, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 1, y: 2 }],
  I5: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 3, y: 0 }, { x: 4, y: 0 }],
  L5: [{ x: 0, y: 0 }, { x: 0, y: 1 }, { x: 0, y: 2 }, { x: 0, y: 3 }, { x: 1, y: 3 }],
  N5: [{ x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 0, y: 2 }, { x: 0, y: 3 }],
  P5: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 0, y: 2 }],
  T5: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }, { x: 1, y: 1 }, { x: 1, y: 2 }],
  U5: [{ x: 0, y: 0 }, { x: 2, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }],
  V5: [{ x: 0, y: 0 }, { x: 0, y: 1 }, { x: 0, y: 2 }, { x: 1, y: 2 }, { x: 2, y: 2 }],
  W5: [{ x: 0, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 1, y: 2 }, { x: 2, y: 2 }],
  X5: [{ x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 1, y: 2 }],
  Y5: [{ x: 1, y: 0 }, { x: 0, y: 1 }, { x: 1, y: 1 }, { x: 1, y: 2 }, { x: 1, y: 3 }],
  Z5: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 1, y: 2 }, { x: 2, y: 2 }],
};

/** Number of squares in a piece. */
export const pieceSize = (pieceId: PieceId): number => PIECES[pieceId].length;

/** A stable, order-independent key for a set of cells (numeric sort, not lexical). */
export const cellsKey = (cells: Cell[]): string =>
  cells
    .map((c) => [c.x, c.y] as const)
    .sort((a, b) => a[0] - b[0] || a[1] - b[1])
    .map(([x, y]) => `${x},${y}`)
    .join('|');

/** Translate cells so that min x = min y = 0. */
export const normalize = (cells: Cell[]): Cell[] => {
  const minX = Math.min(...cells.map((c) => c.x));
  const minY = Math.min(...cells.map((c) => c.y));
  return cells.map((c) => ({ x: c.x - minX, y: c.y - minY }));
};

/** Rotate cells 90° clockwise about the origin: (x, y) → (-y, x). */
const rotate90 = (cells: Cell[]): Cell[] => cells.map((c) => ({ x: -c.y, y: c.x }));

/** Mirror cells across the vertical axis: (x, y) → (-x, y). */
const reflect = (cells: Cell[]): Cell[] => cells.map((c) => ({ x: -c.x, y: c.y }));

const orientationCache = new Map<PieceId, Cell[][]>();

/**
 * All distinct orientations of a piece (normalized), generated by applying the 8
 * elements of the dihedral group D4 (4 rotations × {identity, reflection}) and
 * deduplicating. Results are cached. See GAME_SPEC §2 for expected counts.
 */
export function getOrientations(pieceId: PieceId): Cell[][] {
  const cached = orientationCache.get(pieceId);
  if (cached) return cached;

  const seen = new Map<string, Cell[]>();
  for (const start of [PIECES[pieceId], reflect(PIECES[pieceId])]) {
    let cells = start;
    for (let r = 0; r < 4; r++) {
      const norm = normalize(cells);
      seen.set(cellsKey(norm), norm);
      cells = rotate90(cells);
    }
  }

  const result = [...seen.values()];
  orientationCache.set(pieceId, result);
  return result;
}

/**
 * Resolve a Placement to absolute board cells: reflect (if requested), rotate,
 * normalize, then translate by (placement.x, placement.y).
 */
export function resolveCells(placement: Placement): Cell[] {
  let cells = PIECES[placement.pieceId];
  if (placement.reflected) cells = reflect(cells);
  for (let r = 0; r < placement.rotation; r++) cells = rotate90(cells);
  return normalize(cells).map((c) => ({
    x: c.x + placement.x,
    y: c.y + placement.y,
  }));
}
