/**
 * Post-game replay timeline (product P2 R0). Turns a captured `GameRecord` (its
 * move list + mode/scoring) into a scrubbable sequence of frames — one per ply
 * plus an empty opening frame — each carrying the board snapshot at that point,
 * the move that produced it, the running squares-placed tally per color, and the
 * per-color mobility (open corner attach-points) that P34 M1's chart plots.
 *
 * Pure rules-core module: no React, no boardgame.io, no I/O. The scrubber UI
 * (src/client/recap/) renders these frames; the same builder feeds P15 M2's
 * history-list replay. Every position is regenerated by replaying the moves
 * through the rules core, so a frame can never disagree with the real game.
 */
import type { ByColor, Color, ColorState } from './types';
import { boardSizeOf, createInitialState, playColorsOf } from './modes';
import { pieceSize, resolveCells } from './pieces';
import { applyPlacement, isLegalPlacement } from './placement';
import { attachPoints } from './ai/alphabeta';
import type { GameRecord, LoggedMove } from './ai/selfplay';
import type { GameState } from './types';

export interface RecapFrame {
  /** 0 = empty board (before any move); k = the position after k moves. */
  ply: number;
  /** Flat N×N board snapshot at this ply (N = the variant's board size). */
  board: (Color | null)[];
  /** The move that produced this frame; null only at ply 0. */
  move: LoggedMove | null;
  /** Board indices of `move`'s cells — for a last-move highlight. Empty at ply 0. */
  moveCells: number[];
  /**
   * Per-color state at this ply — remaining inventory, `lastPlaced`, `hasStarted`.
   * A deep clone (the replay mutates one `G` in place), so a review UI can render
   * the player cards + hand tray *at the scrubbed ply* rather than the final
   * position (P2 R0.2). `stuck`/turn cursor aren't replayed here, so `stuck` stays
   * false throughout — a review only needs inventory, score and last-placed, which
   * this carries; whose-turn tags come from `move`.
   */
  colors: ByColor<ColorState>;
  /** Cumulative squares placed per color at this ply (0..89-ish, monotonic). */
  placed: ByColor<number>;
  /**
   * Open corner attach-points per color at this ply — the "room" / mobility read
   * (P34 M1). Rises as a color spreads, falls as opponents wall it in; unlike
   * `placed` it is *not* monotonic, which is exactly what makes the collapse
   * visible. Shares P32's frontier computation (`attachPoints`). At ply 0 every
   * color has its single starting corner (= 1).
   */
  mobility: ByColor<number>;
}

const zeroPlaced = (G: GameState): ByColor<number> =>
  playColorsOf(G).reduce<ByColor<number>>((acc, c) => ((acc[c] = 0), acc), {});

const mobilityOf = (G: GameState): ByColor<number> =>
  playColorsOf(G).reduce<ByColor<number>>((acc, c) => ((acc[c] = attachPoints(G, c)), acc), {});

/**
 * Replay `record.moves` and snapshot every intermediate position. Throws on an
 * illegal move (same discipline as `replayGame`) — a corrupt record must never
 * silently render a bogus timeline. Returns `moves.length + 1` frames.
 */
export function buildRecap(record: GameRecord): RecapFrame[] {
  const G = createInitialState(record.mode, record.scoring, record.variant);
  const size = boardSizeOf(G);
  const placed = zeroPlaced(G);
  const frames: RecapFrame[] = [
    {
      ply: 0,
      board: G.board.slice(),
      move: null,
      moveCells: [],
      placed: { ...placed },
      mobility: mobilityOf(G),
      colors: structuredClone(G.colors),
    },
  ];

  record.moves.forEach((m, i) => {
    const cells = resolveCells(m);
    if (!isLegalPlacement(G, m.color, m.pieceId, cells)) {
      throw new Error(
        `illegal replayed move at ply ${i}: ${m.color} ${m.pieceId} r${m.rotation}${m.reflected ? 'f' : ''} @(${m.x},${m.y})`,
      );
    }
    applyPlacement(G, m.color, m.pieceId, cells);
    placed[m.color] = (placed[m.color] ?? 0) + pieceSize(m.pieceId);
    frames.push({
      ply: i + 1,
      board: G.board.slice(),
      move: m,
      moveCells: cells.map((c) => c.y * size + c.x),
      placed: { ...placed },
      mobility: mobilityOf(G),
      colors: structuredClone(G.colors),
    });
  });

  return frames;
}
