/**
 * Committed Elo ladder artifacts (P62) — the machine-readable form of the pool
 * ratings that until now existed only as prose in a research log (F19).
 *
 * A ladder is scoped to its `(variant × pool)` (M6): Classic ratings are **not**
 * comparable to a Duo ladder, which is a different population and therefore a
 * different scale. There is no cross-variant "strength" here, only per-variant
 * ratings — which is why each artifact names its variant and carries the
 * fingerprint of the pool it was fit from.
 *
 * The artifact is generated by `scripts/experiments/ae21-ladder.ts` from the
 * committed `.result` shard cache; `tests/ladder-artifact.test.ts` holds it against
 * `pool.json` so ratings can't silently outlive the pool that produced them.
 */
import type { Variant } from '../../types';
import classic from './classic.json';

/** One ordered cell of the round-robin: `a`'s game-share vs `b`. */
export interface LadderCell {
  a: string;
  b: string;
  /** Fractional wins / games (ties split). */
  share: number;
  wins: number;
  games: number;
  /** 95% Wilson interval on `share`, as [lo, hi]. */
  ci: [number, number];
}

export interface LadderArtifact {
  schema: 1;
  variant: Variant;
  /** The pool this was fit from, and its strength-bearing fingerprint (see ./hash). */
  pool: { file: string; fingerprint: string; members: string[] };
  /** Where the numbers came from — shard dirs, batch count, and the run that produced them. */
  provenance: {
    generated: string;
    source: string;
    shardDirs: string[];
    batchFiles: number;
  };
  fit: { method: string; centeredOn: number; prior: number };
  /** Bradley-Terry Elo per member, centered so the pool mean is `fit.centeredOn`. */
  elo: Record<string, number>;
  /** Member names strongest-first. */
  ranking: string[];
  /** Named anchors carried over from the pool's tags. */
  anchors: { champion?: string; incumbent?: string };
  /** Every realized ordered cell. Absent pairs mean "never played", not 0%. */
  cells: LadderCell[];
}

/**
 * Classic (20×20, 4 colors) ladder — AE21's pool, re-fit for P62.
 *
 * The double cast is unavoidable: TypeScript widens a JSON array literal to `number[]`,
 * which never narrows to `ci`'s `[number, number]`. Nothing is being papered over —
 * `tests/ladder-artifact.test.ts` validates this file's actual shape at runtime
 * (members rated, ranking ordered, cells coherent, mirrors summing to 1), which is a
 * stronger guarantee than the structural check this cast skips.
 */
export const CLASSIC_LADDER = classic as unknown as LadderArtifact;

/** Rating for a pool member, or `undefined` if it isn't in this ladder. */
export function eloOf(ladder: LadderArtifact, member: string): number | undefined {
  return ladder.elo[member];
}

/** The `a`-vs-`b` cell, or `undefined` if that pairing was never played. */
export function cellOf(ladder: LadderArtifact, a: string, b: string): LadderCell | undefined {
  return ladder.cells.find((c) => c.a === a && c.b === b);
}

/**
 * Rating of the latency-unbounded champion — the strength *ceiling* shippable tiers
 * are measured against (P13's anchor).
 */
export function ceilingOf(ladder: LadderArtifact): number | undefined {
  return ladder.anchors.champion ? ladder.elo[ladder.anchors.champion] : undefined;
}
